/**
 * Default configuration for ClawTaint
 */

import type { ClawTaintConfig } from './schema.js';

export function getDefaultConfig(): ClawTaintConfig {
  return {
    version: '1.0',
    global: {
      enabled: true,
      logLevel: 'info',
    },
    taint: {
      initialLevel: 100,
      penaltyPerUntrustedUrl: 10,
      recoveryPerTrustedUrl: 0,
      minimumLevel: 0,
      thresholds: [
        { minTaint: 75, maxTaint: 100, tier: 'permissive' },
        { minTaint: 50, maxTaint: 74, tier: 'cautious' },
        { minTaint: 25, maxTaint: 49, tier: 'restricted' },
        { minTaint: 0, maxTaint: 24, tier: 'lockdown' },
      ],
    },
    trustedUrls: {
      patterns: [
        '*.github.com',
        '*.stackoverflow.com',
        '*.npmjs.com',
        '*.python.org',
        '*.mozilla.org',
        '*.microsoft.com',
        '*.typescriptlang.org',
        '*.nodejs.org',
        '*.developer.mozilla.org',
      ],
    },
    shellRestrictions: {
      toolNames: ['Bash', 'shell', 'terminal', 'run_command', 'execute'],
      alwaysBlocked: [
        'rm -rf /',
        'mkfs',
        'dd if=',
        ':(){:|:&};:',
        '> /dev/sda',
      ],
      dangerousCommands: [
        'rm -rf',
        'rm -r',
        'rmdir',
        'format',
        'shutdown',
        'reboot',
        'halt',
        'poweroff',
        'init 0',
        'init 6',
        'kill -9',
        'killall',
        'pkill',
        'chmod 777',
        'chmod -R',
        'chown -R',
        'iptables -F',
        'systemctl stop',
        'systemctl disable',
        'DROP TABLE',
        'DROP DATABASE',
        'TRUNCATE',
        'DELETE FROM',
        'curl | sh',
        'curl | bash',
        'wget | sh',
        'wget | bash',
      ],
      safeCommands: [
        'ls',
        'dir',
        'pwd',
        'cd',
        'cat',
        'head',
        'tail',
        'echo',
        'whoami',
        'date',
        'uname',
        'hostname',
        'env',
        'printenv',
        'which',
        'where',
        'type',
        'file',
        'wc',
        'sort',
        'uniq',
        'grep',
        'find',
        'tree',
        'df',
        'du',
        'free',
        'top',
        'ps',
        'uptime',
        'node --version',
        'npm --version',
        'python --version',
        'git status',
        'git log',
        'git diff',
        'git branch',
      ],
    },
  };
}
